// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWcMPwNOlyAzYpZR3zms9YU7Kx8xH8BBU',
    appId: '1:673920635231:web:e299a57c8a6987a17666ea',
    messagingSenderId: '673920635231',
    projectId: 'barkod-project-34684',
    authDomain: 'barkod-project-34684.firebaseapp.com',
    storageBucket: 'barkod-project-34684.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxBxCFcuQ3ICT3g_Zije0Ze92Y6wEkyqI',
    appId: '1:673920635231:android:bb3cb4c9f1938b627666ea',
    messagingSenderId: '673920635231',
    projectId: 'barkod-project-34684',
    storageBucket: 'barkod-project-34684.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsG9Y2BMHnWtYf_enDWwdOEpdP11-l5so',
    appId: '1:673920635231:ios:4d2486ef44fe97337666ea',
    messagingSenderId: '673920635231',
    projectId: 'barkod-project-34684',
    storageBucket: 'barkod-project-34684.appspot.com',
    iosClientId: '673920635231-qlp268rt5udslu7jov31ajj6rt52i0pg.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrCodeAppTemaa',
  );
}
